# Generated by Django 6.0.6 on 2026-06-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
