# Generated by Django 6.0.6 on 2026-06-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoListApp', '0002_remove_todo_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='deleted_at',
        ),
    ]
